- hosts: ios-devices

# This is a playbook for Ansible using network-engine with "show ip vrf interface" parser.
#
# The output of "show ip vrf interface" is shortening all the interface names.
# This playbook renames the interfaces to the longer complete names in the output files.

  roles:
  - ansible-network.network-engine

  tasks:
  - name: run show ip vrf interface
    ios_command:
      commands: 
        - show ip vrf interface
    register: output

    #  - name: Display the output
    #    debug: var=output.stdout

  - name: Parse the output
    command_parser:
      file: "parsers/ios/show_ip_vrf_interface_parser.yml"
      content: "{{ output.stdout[0] }}"


    #  - name: Display the data
    #    debug: var=ip_vrf_interface_facts


  - name: Delete '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    file:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      state: absent

  - name: Write ip_vrf_interface_facts to '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    copy:
      content: "{{ ip_vrf_interface_facts | to_nice_json }}"
      dest: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"


  # Replacing short interface names with the full name.

  - name: Replace short interface name Loopback with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Lo(?=[0-9])'
      replace: '"name": "Loopback'

  - name: Replace short interface name Vlan with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Vl(?=[0-9])'
      replace: '"name": "Vlan'

  - name: Replace short interface name FastEthernet with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Fa(?=[0-9])'
      replace: '"name": "FastEthernet'

  - name: Replace short interface name GigabitEthernet with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Gi(?=[0-9])'
      replace: '"name": "GigabitEthernet'

  - name: Replace short interface name TenGigabitEthernet with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Te(?=[0-9])'
      replace: '"name": "TenGigabitEthernet'

  - name: Replace short interface name FortyGigabitEthernet with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Fo(?=[0-9])'
      replace: '"name": "FortyGigabitEthernet'

  - name: Replace short interface name Port-channel with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "Po(?=[0-9])'
      replace: '"name": "Port-channel'

  - name: Replace short interface name Async with long names in '/tmp/ip_vrf_interface_facts-[inventory_hostname].json'
    replace:
      path: "/tmp/ip_vrf_interface_facts-{{ inventory_hostname }}.json"
      regexp: '"name": "As(?=[0-9])'
      replace: '"name": "Async'


